### ISSUE TITLE
Before I forget

### ISSUE THREAD

**Issue by vsiri** [Up-Next/up-next#72]
- [x]  Change error message on homepage to be more vague because many pages can redirect there now with the @login_required 
- [x]  Push to heroku the new @login_required stuff
- [x] Text bleeds outside playlist (in #81)
- [x] Refresh page resubmits :\ (in #82)
- [x] Ordering breaks
- [x] Error about MAX_INT (in #81)
- [x] Highlighting the boxes when there is a hint (in #81)
