### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by kimberlytze** [Up-Next/up-next#84]
To make our code pretty
- [x] In the method `create_party_in_db` in `create_party.py`, pass in the new party object to `create_playlist` instead of just the party name (in #87)
- [x] In the method `create_playlist` in `create_party.py`, instead of adding each track individually to Spotify, extract all of the uri's in the party's trackset and use the spotipy function to add them all at once (in #87)
- [x] ~~`tracks.py` is gross, I don't know how to make it nicer~~
- [x] `create_party.py` has one massive function (in #90)
